name: Minha Pipeline CI

on: [push]

jobs:
  pipeline:

    runs-on: ubuntu-latest

    steps:

      - name: Baixar código
        uses: actions/checkout@v3

      - name: Mostrar mensagem
        run: echo "Pipeline executando"

      - name: Listar arquivos do projeto
        run: ls
